---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: internal-registry
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/pull-request-service/scaut-v2-dev-secrets-manager-pull-request-service
  dataFrom:
    - scaut-v2-dev/docker-registry-config
  template: 
   type: kubernetes.io/dockerconfigjson

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pull-request-secret
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::454089853750:role/secrets/scaut-v2-dev/pull-request-service/scaut-v2-dev-secrets-manager-pull-request-service
  dataFrom:
    - scaut-v2-dev/pull-request-service/pull-request-service-secret