---
apiVersion: v1
kind: Pod
metadata:
  name: docker-build-pod
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: docker
      image: docker:latest
      tty: true
      command:
        - cat
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
        - name: dockercfg
          mountPath: /root
          readOnly: true
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
    - name: dockercfg
      secret:
        secretName: jenkins-dockercfg-bxzk4
    - name: workspace-volume
      emptyDir:
        medium: Memory
