---
apiVersion: v1
kind: Pod
metadata:
  name: poetry-build-pod
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    - name: python
      image: python:3.7
      tty: true
      command:
        - cat
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: poetrycfg
          mountPath: /home/jenkins/.config/pypoetry
    - name: docker
      image: docker:latest
      tty: true
      command:
        - cat
      securityContext:
        privileged: true
      volumeMounts:
        - name: dockersocket
          mountPath: /var/run/docker.sock
        - name: dockercfg
          mountPath: /root
          readOnly: true
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: openshift
      image: stephen001/oc:latest
      tty: true
      command:
        - cat
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
  volumes:
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
    - name: dockercfg
      secret:
        secretName: jenkins-dockercfg-bxzk4
    - name: poetrycfg
      secret:
        secretName: pypi-config
    - name: workspace-volume
      emptyDir:
        medium: Memory
