---
- name: Pull Request Service Install Checkpoint Start
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Pull Request Service install 'In Progress'
    run_once: true
    set_stats:
      data:
        installer_phase_pull_request:
          title: "Pull Request Service Install"
          playbook: "playbooks/pull-request-service/config.yml"
          status: "In Progress"
          start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: OpenShift Pull Request Service
  hosts: oo_first_master
  roles:
  - role: pull-request-service

- name: Pull Request Service Install Checkpoint End
  hosts: all
  gather_facts: false
  tasks:
  - name: Set Pull Request Service install 'Complete'
    run_once: true
    set_stats:
      data:
        installer_phase_pull_request:
          status: "Complete"
          end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
